name: First test workflow

on: push 

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo # actions example
              uses: actions/checkout@v4 
            - name: Welcome message
              run: echo "Welcome to the ci_cd"
            - name: List file
              run: ls
            - name: Create folder
              run: mkdir NewFolder
            - name: Execute bash file
              run: |
                chmod +x script.sh
                ./script.sh
            